# Generated by Django 5.1.7 on 2025-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='defaultpassword', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=models.TextField(default='defaultconstent'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='user_password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
    ]
