# Generated by Django 5.1.7 on 2025-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_homepage_content_homepage_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title1',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
